[2021-10-10 17:18:26,639] {taskinstance.py:903} INFO - Dependencies all met for <TaskInstance: main.data.scatter_group_data.scatter_data 2021-10-09T00:00:00+00:00 [queued]>
[2021-10-10 17:18:26,644] {taskinstance.py:903} INFO - Dependencies all met for <TaskInstance: main.data.scatter_group_data.scatter_data 2021-10-09T00:00:00+00:00 [queued]>
[2021-10-10 17:18:26,644] {taskinstance.py:1095} INFO - 
--------------------------------------------------------------------------------
[2021-10-10 17:18:26,644] {taskinstance.py:1096} INFO - Starting attempt 1 of 2
[2021-10-10 17:18:26,644] {taskinstance.py:1097} INFO - 
--------------------------------------------------------------------------------
[2021-10-10 17:18:26,652] {taskinstance.py:1115} INFO - Executing <Task(PythonOperator): data.scatter_group_data.scatter_data> on 2021-10-09T00:00:00+00:00
[2021-10-10 17:18:26,653] {standard_task_runner.py:52} INFO - Started process 19757 to run task
[2021-10-10 17:18:26,656] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'main', 'data.scatter_group_data.scatter_data', '2021-10-09T00:00:00+00:00', '--job-id', '570', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/main.py', '--cfg-path', '/tmp/tmpcdqxwxnr', '--error-file', '/tmp/tmpa6u5iqq1']
[2021-10-10 17:18:26,657] {standard_task_runner.py:77} INFO - Job 570: Subtask data.scatter_group_data.scatter_data
[2021-10-10 17:18:26,676] {logging_mixin.py:109} INFO - Running <TaskInstance: main.data.scatter_group_data.scatter_data 2021-10-09T00:00:00+00:00 [running]> on host abd
[2021-10-10 17:18:26,699] {taskinstance.py:1252} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=admin
AIRFLOW_CTX_DAG_ID=main
AIRFLOW_CTX_TASK_ID=data.scatter_group_data.scatter_data
AIRFLOW_CTX_EXECUTION_DATE=2021-10-09T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-10-09T00:00:00+00:00
[2021-10-10 17:18:26,699] {python.py:151} INFO - Done. Returned value was: None
[2021-10-10 17:18:26,702] {taskinstance.py:1212} INFO - Marking task as SUCCESS. dag_id=main, task_id=data.scatter_group_data.scatter_data, execution_date=20211009T000000, start_date=20211010T141826, end_date=20211010T141826
[2021-10-10 17:18:26,747] {local_task_job.py:151} INFO - Task exited with return code 0
[2021-10-10 17:18:26,790] {local_task_job.py:261} INFO - 5 downstream tasks scheduled from follow-on schedule check
[2021-10-10 17:27:54,210] {taskinstance.py:903} INFO - Dependencies all met for <TaskInstance: main.data.scatter_group_data.scatter_data 2021-10-09T00:00:00+00:00 [queued]>
[2021-10-10 17:27:54,216] {taskinstance.py:903} INFO - Dependencies all met for <TaskInstance: main.data.scatter_group_data.scatter_data 2021-10-09T00:00:00+00:00 [queued]>
[2021-10-10 17:27:54,216] {taskinstance.py:1095} INFO - 
--------------------------------------------------------------------------------
[2021-10-10 17:27:54,216] {taskinstance.py:1096} INFO - Starting attempt 1 of 2
[2021-10-10 17:27:54,216] {taskinstance.py:1097} INFO - 
--------------------------------------------------------------------------------
[2021-10-10 17:27:54,224] {taskinstance.py:1115} INFO - Executing <Task(PythonOperator): data.scatter_group_data.scatter_data> on 2021-10-09T00:00:00+00:00
[2021-10-10 17:27:54,225] {standard_task_runner.py:52} INFO - Started process 21496 to run task
[2021-10-10 17:27:54,228] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'main', 'data.scatter_group_data.scatter_data', '2021-10-09T00:00:00+00:00', '--job-id', '570', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/main.py', '--cfg-path', '/tmp/tmpy6qx53p0', '--error-file', '/tmp/tmps7685tjx']
[2021-10-10 17:27:54,228] {standard_task_runner.py:77} INFO - Job 570: Subtask data.scatter_group_data.scatter_data
[2021-10-10 17:27:54,247] {logging_mixin.py:109} INFO - Running <TaskInstance: main.data.scatter_group_data.scatter_data 2021-10-09T00:00:00+00:00 [running]> on host abd
[2021-10-10 17:27:54,274] {taskinstance.py:1252} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=admin
AIRFLOW_CTX_DAG_ID=main
AIRFLOW_CTX_TASK_ID=data.scatter_group_data.scatter_data
AIRFLOW_CTX_EXECUTION_DATE=2021-10-09T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-10-09T00:00:00+00:00
[2021-10-10 17:27:54,275] {python.py:151} INFO - Done. Returned value was: None
[2021-10-10 17:27:54,280] {taskinstance.py:1212} INFO - Marking task as SUCCESS. dag_id=main, task_id=data.scatter_group_data.scatter_data, execution_date=20211009T000000, start_date=20211010T142754, end_date=20211010T142754
[2021-10-10 17:27:54,319] {local_task_job.py:151} INFO - Task exited with return code 0
[2021-10-10 17:27:54,338] {local_task_job.py:261} INFO - 5 downstream tasks scheduled from follow-on schedule check
[2021-10-10 17:31:30,661] {taskinstance.py:903} INFO - Dependencies all met for <TaskInstance: main.data.scatter_group_data.scatter_data 2021-10-09T00:00:00+00:00 [queued]>
[2021-10-10 17:31:30,670] {taskinstance.py:903} INFO - Dependencies all met for <TaskInstance: main.data.scatter_group_data.scatter_data 2021-10-09T00:00:00+00:00 [queued]>
[2021-10-10 17:31:30,670] {taskinstance.py:1095} INFO - 
--------------------------------------------------------------------------------
[2021-10-10 17:31:30,670] {taskinstance.py:1096} INFO - Starting attempt 1 of 2
[2021-10-10 17:31:30,670] {taskinstance.py:1097} INFO - 
--------------------------------------------------------------------------------
[2021-10-10 17:31:30,677] {taskinstance.py:1115} INFO - Executing <Task(PythonOperator): data.scatter_group_data.scatter_data> on 2021-10-09T00:00:00+00:00
[2021-10-10 17:31:30,679] {standard_task_runner.py:52} INFO - Started process 22116 to run task
[2021-10-10 17:31:30,683] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'main', 'data.scatter_group_data.scatter_data', '2021-10-09T00:00:00+00:00', '--job-id', '570', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/main.py', '--cfg-path', '/tmp/tmp0afkkfar', '--error-file', '/tmp/tmpimtss3j6']
[2021-10-10 17:31:30,683] {standard_task_runner.py:77} INFO - Job 570: Subtask data.scatter_group_data.scatter_data
[2021-10-10 17:31:30,703] {logging_mixin.py:109} INFO - Running <TaskInstance: main.data.scatter_group_data.scatter_data 2021-10-09T00:00:00+00:00 [running]> on host abd
[2021-10-10 17:31:30,739] {taskinstance.py:1252} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=admin
AIRFLOW_CTX_DAG_ID=main
AIRFLOW_CTX_TASK_ID=data.scatter_group_data.scatter_data
AIRFLOW_CTX_EXECUTION_DATE=2021-10-09T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-10-09T00:00:00+00:00
[2021-10-10 17:31:30,739] {python.py:151} INFO - Done. Returned value was: None
[2021-10-10 17:31:30,741] {taskinstance.py:1212} INFO - Marking task as SUCCESS. dag_id=main, task_id=data.scatter_group_data.scatter_data, execution_date=20211009T000000, start_date=20211010T143130, end_date=20211010T143130
[2021-10-10 17:31:30,773] {local_task_job.py:151} INFO - Task exited with return code 0
[2021-10-10 17:31:30,790] {local_task_job.py:261} INFO - 5 downstream tasks scheduled from follow-on schedule check
[2021-10-10 19:36:15,005] {taskinstance.py:903} INFO - Dependencies all met for <TaskInstance: main.data.scatter_group_data.scatter_data 2021-10-09T00:00:00+00:00 [queued]>
[2021-10-10 19:36:15,017] {taskinstance.py:903} INFO - Dependencies all met for <TaskInstance: main.data.scatter_group_data.scatter_data 2021-10-09T00:00:00+00:00 [queued]>
[2021-10-10 19:36:15,017] {taskinstance.py:1095} INFO - 
--------------------------------------------------------------------------------
[2021-10-10 19:36:15,017] {taskinstance.py:1096} INFO - Starting attempt 1 of 2
[2021-10-10 19:36:15,017] {taskinstance.py:1097} INFO - 
--------------------------------------------------------------------------------
[2021-10-10 19:36:15,026] {taskinstance.py:1115} INFO - Executing <Task(PythonOperator): data.scatter_group_data.scatter_data> on 2021-10-09T00:00:00+00:00
[2021-10-10 19:36:15,028] {standard_task_runner.py:52} INFO - Started process 55714 to run task
[2021-10-10 19:36:15,033] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'main', 'data.scatter_group_data.scatter_data', '2021-10-09T00:00:00+00:00', '--job-id', '570', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/main.py', '--cfg-path', '/tmp/tmp2shw21r2', '--error-file', '/tmp/tmpo9bzlik1']
[2021-10-10 19:36:15,033] {standard_task_runner.py:77} INFO - Job 570: Subtask data.scatter_group_data.scatter_data
[2021-10-10 19:36:15,057] {logging_mixin.py:109} INFO - Running <TaskInstance: main.data.scatter_group_data.scatter_data 2021-10-09T00:00:00+00:00 [running]> on host abd
[2021-10-10 19:36:15,082] {taskinstance.py:1252} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=admin
AIRFLOW_CTX_DAG_ID=main
AIRFLOW_CTX_TASK_ID=data.scatter_group_data.scatter_data
AIRFLOW_CTX_EXECUTION_DATE=2021-10-09T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-10-09T00:00:00+00:00
[2021-10-10 19:36:15,083] {python.py:151} INFO - Done. Returned value was: None
[2021-10-10 19:36:15,086] {taskinstance.py:1212} INFO - Marking task as SUCCESS. dag_id=main, task_id=data.scatter_group_data.scatter_data, execution_date=20211009T000000, start_date=20211010T163615, end_date=20211010T163615
[2021-10-10 19:36:15,123] {local_task_job.py:151} INFO - Task exited with return code 0
[2021-10-10 19:36:15,139] {local_task_job.py:261} INFO - 5 downstream tasks scheduled from follow-on schedule check
[2021-10-10 19:45:54,749] {taskinstance.py:903} INFO - Dependencies all met for <TaskInstance: main.data.scatter_group_data.scatter_data 2021-10-09T00:00:00+00:00 [queued]>
[2021-10-10 19:45:54,756] {taskinstance.py:903} INFO - Dependencies all met for <TaskInstance: main.data.scatter_group_data.scatter_data 2021-10-09T00:00:00+00:00 [queued]>
[2021-10-10 19:45:54,756] {taskinstance.py:1095} INFO - 
--------------------------------------------------------------------------------
[2021-10-10 19:45:54,756] {taskinstance.py:1096} INFO - Starting attempt 1 of 2
[2021-10-10 19:45:54,756] {taskinstance.py:1097} INFO - 
--------------------------------------------------------------------------------
[2021-10-10 19:45:54,764] {taskinstance.py:1115} INFO - Executing <Task(PythonOperator): data.scatter_group_data.scatter_data> on 2021-10-09T00:00:00+00:00
[2021-10-10 19:45:54,766] {standard_task_runner.py:52} INFO - Started process 59015 to run task
[2021-10-10 19:45:54,769] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'main', 'data.scatter_group_data.scatter_data', '2021-10-09T00:00:00+00:00', '--job-id', '570', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/main.py', '--cfg-path', '/tmp/tmpdal_h8fs', '--error-file', '/tmp/tmpnz77l9oa']
[2021-10-10 19:45:54,769] {standard_task_runner.py:77} INFO - Job 570: Subtask data.scatter_group_data.scatter_data
[2021-10-10 19:45:54,794] {logging_mixin.py:109} INFO - Running <TaskInstance: main.data.scatter_group_data.scatter_data 2021-10-09T00:00:00+00:00 [running]> on host abd
[2021-10-10 19:45:54,821] {taskinstance.py:1252} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=admin
AIRFLOW_CTX_DAG_ID=main
AIRFLOW_CTX_TASK_ID=data.scatter_group_data.scatter_data
AIRFLOW_CTX_EXECUTION_DATE=2021-10-09T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-10-09T00:00:00+00:00
[2021-10-10 19:45:54,821] {python.py:151} INFO - Done. Returned value was: None
[2021-10-10 19:45:54,825] {taskinstance.py:1212} INFO - Marking task as SUCCESS. dag_id=main, task_id=data.scatter_group_data.scatter_data, execution_date=20211009T000000, start_date=20211010T164554, end_date=20211010T164554
[2021-10-10 19:45:54,859] {local_task_job.py:151} INFO - Task exited with return code 0
[2021-10-10 19:45:54,875] {local_task_job.py:261} INFO - 5 downstream tasks scheduled from follow-on schedule check
[2021-10-10 19:55:47,028] {taskinstance.py:903} INFO - Dependencies all met for <TaskInstance: main.data.scatter_group_data.scatter_data 2021-10-09T00:00:00+00:00 [queued]>
[2021-10-10 19:55:47,034] {taskinstance.py:903} INFO - Dependencies all met for <TaskInstance: main.data.scatter_group_data.scatter_data 2021-10-09T00:00:00+00:00 [queued]>
[2021-10-10 19:55:47,034] {taskinstance.py:1095} INFO - 
--------------------------------------------------------------------------------
[2021-10-10 19:55:47,034] {taskinstance.py:1096} INFO - Starting attempt 1 of 2
[2021-10-10 19:55:47,034] {taskinstance.py:1097} INFO - 
--------------------------------------------------------------------------------
[2021-10-10 19:55:47,042] {taskinstance.py:1115} INFO - Executing <Task(PythonOperator): data.scatter_group_data.scatter_data> on 2021-10-09T00:00:00+00:00
[2021-10-10 19:55:47,043] {standard_task_runner.py:52} INFO - Started process 62618 to run task
[2021-10-10 19:55:47,046] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'main', 'data.scatter_group_data.scatter_data', '2021-10-09T00:00:00+00:00', '--job-id', '571', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/main.py', '--cfg-path', '/tmp/tmpk6ptqss8', '--error-file', '/tmp/tmpkwb2g895']
[2021-10-10 19:55:47,047] {standard_task_runner.py:77} INFO - Job 571: Subtask data.scatter_group_data.scatter_data
[2021-10-10 19:55:47,067] {logging_mixin.py:109} INFO - Running <TaskInstance: main.data.scatter_group_data.scatter_data 2021-10-09T00:00:00+00:00 [running]> on host abd
[2021-10-10 19:55:47,089] {taskinstance.py:1252} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=admin
AIRFLOW_CTX_DAG_ID=main
AIRFLOW_CTX_TASK_ID=data.scatter_group_data.scatter_data
AIRFLOW_CTX_EXECUTION_DATE=2021-10-09T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-10-09T00:00:00+00:00
[2021-10-10 19:55:47,090] {python.py:151} INFO - Done. Returned value was: None
[2021-10-10 19:55:47,092] {taskinstance.py:1212} INFO - Marking task as SUCCESS. dag_id=main, task_id=data.scatter_group_data.scatter_data, execution_date=20211009T000000, start_date=20211010T165547, end_date=20211010T165547
[2021-10-10 19:55:47,137] {local_task_job.py:151} INFO - Task exited with return code 0
[2021-10-10 19:55:47,162] {local_task_job.py:261} INFO - 5 downstream tasks scheduled from follow-on schedule check
[2021-10-10 20:17:16,532] {taskinstance.py:903} INFO - Dependencies all met for <TaskInstance: main.data.scatter_group_data.scatter_data 2021-10-09T00:00:00+00:00 [queued]>
[2021-10-10 20:17:16,538] {taskinstance.py:903} INFO - Dependencies all met for <TaskInstance: main.data.scatter_group_data.scatter_data 2021-10-09T00:00:00+00:00 [queued]>
[2021-10-10 20:17:16,538] {taskinstance.py:1095} INFO - 
--------------------------------------------------------------------------------
[2021-10-10 20:17:16,538] {taskinstance.py:1096} INFO - Starting attempt 1 of 2
[2021-10-10 20:17:16,538] {taskinstance.py:1097} INFO - 
--------------------------------------------------------------------------------
[2021-10-10 20:17:16,545] {taskinstance.py:1115} INFO - Executing <Task(PythonOperator): data.scatter_group_data.scatter_data> on 2021-10-09T00:00:00+00:00
[2021-10-10 20:17:16,546] {standard_task_runner.py:52} INFO - Started process 9630 to run task
[2021-10-10 20:17:16,549] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'main', 'data.scatter_group_data.scatter_data', '2021-10-09T00:00:00+00:00', '--job-id', '572', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/main.py', '--cfg-path', '/tmp/tmpbgithj1j', '--error-file', '/tmp/tmpp2rbyvcn']
[2021-10-10 20:17:16,549] {standard_task_runner.py:77} INFO - Job 572: Subtask data.scatter_group_data.scatter_data
[2021-10-10 20:17:16,568] {logging_mixin.py:109} INFO - Running <TaskInstance: main.data.scatter_group_data.scatter_data 2021-10-09T00:00:00+00:00 [running]> on host abd
[2021-10-10 20:17:16,602] {taskinstance.py:1252} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=admin
AIRFLOW_CTX_DAG_ID=main
AIRFLOW_CTX_TASK_ID=data.scatter_group_data.scatter_data
AIRFLOW_CTX_EXECUTION_DATE=2021-10-09T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-10-09T00:00:00+00:00
[2021-10-10 20:17:16,603] {python.py:151} INFO - Done. Returned value was: None
[2021-10-10 20:17:16,606] {taskinstance.py:1212} INFO - Marking task as SUCCESS. dag_id=main, task_id=data.scatter_group_data.scatter_data, execution_date=20211009T000000, start_date=20211010T171716, end_date=20211010T171716
[2021-10-10 20:17:16,640] {local_task_job.py:151} INFO - Task exited with return code 0
[2021-10-10 20:17:16,676] {local_task_job.py:261} INFO - 5 downstream tasks scheduled from follow-on schedule check
[2021-10-10 20:36:42,154] {taskinstance.py:903} INFO - Dependencies all met for <TaskInstance: main.data.scatter_group_data.scatter_data 2021-10-09T00:00:00+00:00 [queued]>
[2021-10-10 20:36:42,161] {taskinstance.py:903} INFO - Dependencies all met for <TaskInstance: main.data.scatter_group_data.scatter_data 2021-10-09T00:00:00+00:00 [queued]>
[2021-10-10 20:36:42,161] {taskinstance.py:1095} INFO - 
--------------------------------------------------------------------------------
[2021-10-10 20:36:42,161] {taskinstance.py:1096} INFO - Starting attempt 1 of 2
[2021-10-10 20:36:42,161] {taskinstance.py:1097} INFO - 
--------------------------------------------------------------------------------
[2021-10-10 20:36:42,168] {taskinstance.py:1115} INFO - Executing <Task(PythonOperator): data.scatter_group_data.scatter_data> on 2021-10-09T00:00:00+00:00
[2021-10-10 20:36:42,170] {standard_task_runner.py:52} INFO - Started process 14181 to run task
[2021-10-10 20:36:42,173] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'main', 'data.scatter_group_data.scatter_data', '2021-10-09T00:00:00+00:00', '--job-id', '572', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/main.py', '--cfg-path', '/tmp/tmpto94gfbm', '--error-file', '/tmp/tmpmsnpbpl4']
[2021-10-10 20:36:42,173] {standard_task_runner.py:77} INFO - Job 572: Subtask data.scatter_group_data.scatter_data
[2021-10-10 20:36:42,192] {logging_mixin.py:109} INFO - Running <TaskInstance: main.data.scatter_group_data.scatter_data 2021-10-09T00:00:00+00:00 [running]> on host abd
[2021-10-10 20:36:42,213] {taskinstance.py:1252} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=admin
AIRFLOW_CTX_DAG_ID=main
AIRFLOW_CTX_TASK_ID=data.scatter_group_data.scatter_data
AIRFLOW_CTX_EXECUTION_DATE=2021-10-09T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-10-09T00:00:00+00:00
[2021-10-10 20:36:42,214] {python.py:151} INFO - Done. Returned value was: None
[2021-10-10 20:36:42,216] {taskinstance.py:1212} INFO - Marking task as SUCCESS. dag_id=main, task_id=data.scatter_group_data.scatter_data, execution_date=20211009T000000, start_date=20211010T173642, end_date=20211010T173642
[2021-10-10 20:36:42,263] {local_task_job.py:151} INFO - Task exited with return code 0
[2021-10-10 20:36:42,286] {local_task_job.py:261} INFO - 5 downstream tasks scheduled from follow-on schedule check
